GET http://localhost:5129/todos
###
POST http://localhost:5129/todos
Content-Type: application/json

{
    "id":2,
    "name":"Write a 2 demo",
    "dueDate":"2024-11-20",
    "isCompleted":false
}
###
GET http://localhost:5129/todos/2
###
DELETE http://localhost:5129/todos/1
###
GET http://localhost:5129/tasks/2